server:
  port: 8456

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${ATLAS_URI}
  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME:user}
      password: ${SPRING_SECURITY_USER_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: "oogabooga123oogabooga123oogabooga123!"
  expirationMs: 86400000

#    // Expiration: 1 day (configurable)
#    // 600000 // 10 min
#    // 300000 // 5 minutes
#    // 60000  // 1 minute

logging:
  level:
    org.springframework.security: DEBUG